version: '2.6'
services:

  db:
    container_name: battleship-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: battleship-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
