spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/batallaNaval-db
#    url: jdbc:postgresql://db:5436/compose-batallaNaval-db
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update